/* Shared authenticated batch status + media flow for Production and QR Station. */
(function(){
'use strict';
var statuses=['Created','Start Producing','Print Finish','Outsource','QC Pass','Shipped'];
var labels=['รอผลิต','กำลังผลิต','พิมพ์เสร็จ','ส่งภายนอก','QC ผ่าน','จัดส่งแล้ว'];
var types=['image/jpeg','image/png','image/webp','video/mp4','video/webm','video/quicktime'];
var dialog=document.createElement('dialog');dialog.className='axis-media-panel';dialog.setAttribute('aria-labelledby','axis-batch-title');
dialog.innerHTML='<header><div><p>BATCH STATUS / EVIDENCE</p><h2 id="axis-batch-title"></h2></div><button type="button" data-close aria-label="ปิด">ปิด</button></header><form><label>สถานะใหม่<select name="status" required></select></label><label>หมายเหตุ<textarea name="notes" rows="2" maxlength="3000" placeholder="รายละเอียดการทำงานหรือผลตรวจสอบ"></textarea></label><div class="axis-media-upload"><label>แนบรูปหรือวิดีโอ<input type="file" name="media" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime" multiple></label><div class="axis-media-hint">สูงสุด 5 ไฟล์ · ไฟล์ละ 8 MB · รวม 20 MB<br>JPG / PNG / WebP / MP4 / WebM / MOV</div></div><div class="axis-media-previews" data-previews></div><p role="alert" data-error></p><p aria-live="polite" data-message></p><div class="axis-media-actions"><button type="button" data-cancel>ยกเลิก</button><button type="submit">บันทึกสถานะพร้อมไฟล์แนบ</button></div></form><section><h3>ประวัติสถานะและไฟล์แนบ</h3><p class="axis-media-hint">ไฟล์เก็บใน Google Drive · การเปิดไฟล์ใช้สิทธิ์ของโฟลเดอร์หลักฐาน</p><div data-history aria-live="polite"></div></section>';
document.body.appendChild(dialog);
var form=dialog.querySelector('form'),select=form.elements.status,input=form.elements.media,notes=form.elements.notes,previews=dialog.querySelector('[data-previews]'),error=dialog.querySelector('[data-error]'),message=dialog.querySelector('[data-message]'),history=dialog.querySelector('[data-history]'),save=form.querySelector('[type=submit]');
statuses.forEach(function(status,i){var option=document.createElement('option');option.value=status;option.textContent=labels[i];select.appendChild(option);});
var selected=[],config=null,pending=null,busy=false,version=0;
function token(){return sessionStorage.getItem('sn_token')||localStorage.getItem('sn_token')||'';}
function api(){return window.API || window.API_URL;}
function release(){selected.forEach(function(item){URL.revokeObjectURL(item.url);});selected=[];previews.replaceChildren();input.value='';}
function invalidate(){if(!busy)pending=null;}
function setBusy(value){busy=value;form.querySelectorAll('input,select,textarea,button').forEach(function(e){e.disabled=value;});dialog.querySelector('[data-close]').disabled=value;}
function addPreview(item){var tile=document.createElement('article');tile.className='axis-media-tile';var media=document.createElement(item.file.type.indexOf('video/')===0?'video':'img');media.src=item.url;if(media.tagName==='VIDEO'){media.controls=true;media.preload='metadata';media.playsInline=true;media.setAttribute('aria-label',item.file.name);}else{media.alt=item.file.name;}tile.appendChild(media);var p=document.createElement('p');p.textContent=item.file.name+' · '+(item.file.size/1048576).toFixed(1)+' MB';tile.appendChild(p);var remove=document.createElement('button');remove.type='button';remove.textContent='นำไฟล์ออก';remove.addEventListener('click',function(){if(busy)return;selected=selected.filter(function(x){return x!==item;});URL.revokeObjectURL(item.url);tile.remove();invalidate();});tile.appendChild(remove);previews.appendChild(tile);}
input.addEventListener('change',function(){error.textContent='';Array.from(input.files).forEach(function(file){var total=selected.reduce(function(sum,x){return sum+x.file.size;},0);if(types.indexOf(file.type)<0){error.textContent='ชนิดไฟล์ไม่รองรับ โปรดเลือก JPG, PNG, WebP, MP4, WebM หรือ MOV';return;}if(!file.size||file.size>8*1048576){error.textContent='แต่ละไฟล์ต้องมีขนาดไม่เกิน 8 MB';return;}if(selected.length>=5||total+file.size>20*1048576){error.textContent='แนบได้สูงสุด 5 ไฟล์ รวมไม่เกิน 20 MB';return;}var item={file:file,url:URL.createObjectURL(file)};selected.push(item);addPreview(item);});input.value='';invalidate();});
notes.addEventListener('input',invalidate);select.addEventListener('change',invalidate);
function paintHistory(entries){history.replaceChildren();if(!entries.length){history.textContent='ยังไม่มีประวัติที่บันทึกพร้อมหลักฐาน';return;}entries.forEach(function(entry){var card=document.createElement('article');card.className='axis-media-history';var title=document.createElement('div');title.textContent=(labels[statuses.indexOf(entry.status)]||entry.status)+' · '+entry.timestamp;card.appendChild(title);var meta=document.createElement('p');meta.textContent=entry.operator||'';card.appendChild(meta);if(entry.notes){var p=document.createElement('p');p.textContent=entry.notes;card.appendChild(p);}(entry.attachments||[]).forEach(function(file){if(!/^https:\/\/drive\.google\.com\//.test(file.url||''))return;var a=document.createElement('a');a.href=file.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=(file.mime.indexOf('video/')===0?'วิดีโอ · ':'รูปภาพ · ')+file.name;card.appendChild(a);});history.appendChild(card);});}
function loadHistory(){var current=version,id=config.batchId;history.textContent='กำลังโหลดประวัติ…';return snFetch(api()+'?api=batchHistory&batchId='+encodeURIComponent(id)+'&token='+encodeURIComponent(token()),{cache:'no-store'}).then(function(r){return r.json();}).then(function(d){if(current!==version)return;if(!d.success||!Array.isArray(d.history))throw Error(d.error||'ต้องอัปเดต backend ก่อนใช้ประวัติไฟล์แนบ');paintHistory(d.history);}).catch(function(err){if(current===version)history.textContent='โหลดประวัติไม่ได้: '+err.message;});}
function close(){if(busy)return;dialog.close();release();version++;}
dialog.querySelector('[data-close]').addEventListener('click',close);dialog.querySelector('[data-cancel]').addEventListener('click',close);dialog.addEventListener('cancel',function(e){if(busy)e.preventDefault();});dialog.addEventListener('close',function(){if(!busy){release();version++;}});
window.snOpenBatchStatus=function(options){if(busy)return;config=options;version++;release();pending=null;error.textContent='';message.textContent='';notes.value=options.notes||'';select.value=statuses.indexOf(options.status)>=0?options.status:'Created';document.getElementById('axis-batch-title').textContent=options.batchId+(options.product?' · '+options.product:'');if(!dialog.open)dialog.showModal();loadHistory();};
function encoded(file){return new Promise(function(resolve,reject){var reader=new FileReader();reader.onload=function(){var data=String(reader.result),comma=data.indexOf(',');if(comma<0){reject(Error('อ่านไฟล์ไม่ได้'));return;}resolve({name:file.name,mime:file.type,data:data.slice(comma+1)});};reader.onerror=function(){reject(Error('อ่านไฟล์ '+file.name+' ไม่ได้'));};reader.readAsDataURL(file);});}
function requestId(){return 'sn_'+(crypto.randomUUID?crypto.randomUUID().replace(/-/g,''):Date.now().toString(36)+Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2));}
form.addEventListener('submit',async function(e){e.preventDefault();if(busy||!config)return;error.textContent='';setBusy(true);message.textContent=selected.length?'กำลังเตรียมไฟล์และบันทึก กรุณารอสักครู่…':'กำลังบันทึกสถานะ…';
try{if(!pending){var files=[];for(var item of selected)files.push(await encoded(item.file));pending={action:'update_status_media',token:token(),batchId:config.batchId,status:select.value,notes:notes.value,requestId:requestId(),files:files};}else pending.token=token();
var response=await snFetch(api(),{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify(pending)});var data=await response.json();if(!data.success)throw Error(data.error||'บันทึกไม่สำเร็จ ต้องอัปเดต backend ก่อนใช้ไฟล์แนบ');
message.textContent='บันทึกแล้ว · '+(labels[statuses.indexOf(data.entry.status)]||data.entry.status)+' · แนบ '+data.entry.attachments.length+' ไฟล์';pending=null;release();notes.value='';await loadHistory();if(config.onSaved)config.onSaved(data);if(window.toast)window.toast('บันทึกสถานะและไฟล์แนบแล้ว','ok');
}catch(err){error.textContent=err.message+' · หากการเชื่อมต่อขาด ให้กดบันทึกซ้ำโดยไม่แก้ข้อมูล เพื่อป้องกันรายการซ้ำ';message.textContent='';}finally{setBusy(false);}
});
})();
